### ISSUE TITLE
Babel presets missing in `package.json`

### ISSUE THREAD

**Issue by RodrigoRoaRodriguez** [fazeaction/webpack-threejs-boilerplate#1]
To get this to work I had to run:
```
npm install --save-dev babel-preset-stage-0
npm install --save-dev babel-preset-react
```
You might have forgot the `--save-dev` flag when you installed the presets. Other than that thanks for the boilerplate.

**Comment by fazeaction** [comment]
Hi Rodrigo! Glad you like it. I've run a clean git clone for the project without problems. Please, can you tell me why these presets are needed? I try to get packcage.json with minimun dependencies.

**Comment by RodrigoRoaRodriguez** [comment]
Hello, you are right. The fault was on my end. I did a clean install in a new computer and it did not prompt me for any these. After some experimentation I realized that this had to do with an astray `.babelrc` dotfile that had somehow ended up in my project folder. Hence, I apologize for wasting your time.
