### ISSUE TITLE
Feature request: Source maps for javascript

### ISSUE THREAD

**Issue by dionsnoeijen** [fazeaction/webpack-threejs-boilerplate#3]
Everything is compiled which is great, except while developing. Adding source maps for js would be very nice.

**Comment by fazeaction** [comment]
Sorry to answer late. I just updated the boilerplate with a more updated configuration for webpack and sourcemaps are activated in [development](https://github.com/fazeaction/webpack-threejs-boilerplate/blob/d6d35aa5bb475bb00bf1e0eed7c861484ca0955f/config/index.js#L36)
Let me know if it solve this issue.
